Vagrant.require_version ">= 2.0.0"

boxes = [
    {
        :name => "master",
        :eth1 => "192.168.56.35",
        :mem => "4096",
        :cpu => "2"
    },
    {
        :name => "worker1",
        :eth1 => "192.168.56.36",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "worker2",
        :eth1 => "192.168.56.37",
        :mem => "2048",
        :cpu => "2"
    }

]

Vagrant.configure(2) do |config|
    config.vm.box ="bento/ubuntu-20.04"
  
    boxes.each do |opts|
        config.vm.define opts[:name] do |config|
          config.vm.provision "shell", path: "launched.sh"
          config.vm.hostname = opts[:name]
          config.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--memory", opts[:mem]]
            v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
  
          end
          config.vm.network :private_network, ip: opts[:eth1]
        end
    end
  end
