apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  namespace: development
  labels:
    run: jekyll
spec:
  initContainers:
  - name: copy-jekyll-site
    image: kodekloud/jekyll
    command: [ 'sh', '-c', 'jekyll new /site' ] 
    volumeMounts:
    - mountPath: /site
      name: site
  containers:
  - name: jekyll
    image: kodekloud/jekyll-serve
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /site
      name: site
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site